Updated to fix variables

diff --git a/bin/chkarray b/bin/chkarray
--- a/bin/chkarray
+++ b/bin/chkarray
@@ -6,17 +6,27 @@
 # documentation: https://incowk01/wiki/index.php/Sysadmin_Tools
 # update script to loop through servers so a special script doesn't have to be written for each server
 
-PROGNAME="chkarray"
-CONTENT="chkarray"
+BASENAME=$(basename "${0}")
+DIRNAME=$(dirname "${0}")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
+CONTENT="${BASENAME}"
 TIMEOUT=40
-HOSTNAME=`hostname|cut -f1 -d.`
 # Set this to one of the servers in the Tru64 cluster. It keeps it from running more than once and causing an error. The other side will just exit.
 OSF1SVRS="bart crdb0 crdb1 homer ips0 ips1 lldb01 lmpc0a"
 
 if [[ -z $1 ]]
 then
   DEBUG='no'
-  LOG=/opt/intrado/etc/chkarray.output
+  LOG=${SCRIPTS}/etc/${BASENAME}.output
 else
   if [[ $1 = "help" ]]
   then
@@ -27,40 +37,40 @@ else
     echo " debug - tells the script to generate the logs necessary for troubleshooting"
     echo ""
     echo "The following command gives you access to the SAN:"
-    FLAGS=`/sbin/hwmgr -show scsi | /sbin/grep scp | /usr/bin/cut -f2 -d\[ | /usr/bin/cut -f1 -d\] | /usr/bin/awk -F/ '{print "-b"$1" -t"$2" -l"$3}'`
+    FLAGS=$(/sbin/hwmgr -show scsi | /sbin/grep scp | /usr/bin/cut -f2 -d\[ | /usr/bin/cut -f1 -d\] | /usr/bin/awk -F/ '{print "-b"$1" -t"$2" -l"$3}')
     echo "/usr/lbin/hsxterm5 $FLAGS"
     exit 0
   else
     DEBUG='yes'
-    LOG=/opt/intrado/etc/chkarray.debug
+    LOG=${SCRIPTS}/etc/${BASENAME}.debug
   fi
 fi  
 
 # the OSF1SVRS variable should be run on all OSF servers except the second node of a cluster.
-for i in $OSF1SVRS
+for i in ${OSF1SVRS}
 do
-  if [[ $i = $HOSTNAME ]]
+  if [[ ${i} = "${HOSTNAME}" ]]
   then
 
-    FLAGS=`/sbin/hwmgr -show scsi | /sbin/grep scp | /usr/bin/cut -f2 -d\[ | /usr/bin/cut -f1 -d\] | /usr/bin/awk -F/ '{print "-b"$1" -t"$2" -l"$3}'`
+    FLAGS=$(/sbin/hwmgr -show scsi | /sbin/grep scp | /usr/bin/cut -f2 -d\[ | /usr/bin/cut -f1 -d\] | /usr/bin/awk -F/ '{print "-b"$1" -t"$2" -l"$3}')
 
 # Delete the old output file. This lets us know if there's a problem 
 # with the tool completing
 
-    if [[ -f /opt/intrado/etc/$CONTENT.output ]]
+    if [[ -f ${SCRIPTS}/etc/${CONTENT}.output ]]
     then
-      rm /opt/intrado/etc/$CONTENT.output
+      rm "${SCRIPTS}/etc/${CONTENT}.output"
     fi
 
-    if [[ -z $FLAGS ]]
+    if [[ -z ${FLAGS} ]]
     then
-      echo "No raid devices" >> $LOG
+      echo "No raid devices" >> "${LOG}"
       exit 0
     fi
 
-    if [[ $DEBUG = 'no' ]]
+    if [[ ${DEBUG} = 'no' ]]
     then
-      /usr/lbin/hsxterm5 $FLAGS >> $LOG 2>&1 << EOF
+      /usr/lbin/hsxterm5 "${FLAGS}" >> "${LOG}" 2>&1 << EOF
 show disk
 quit
 EOF
@@ -69,7 +79,7 @@ EOF
 # I removed the ! portion of both commands but here is what they ask for:
 # show remote full !for DRM configuration
 # show assoc full !for DRM configuration
-      /usr/lbin/hsxterm5 $FLAGS >> $LOG 2>&1 << DEBUGEOF
+      /usr/lbin/hsxterm5 "${FLAGS}" >> "${LOG}" 2>&1 << DEBUGEOF
 show this full
 show other full
 show connection full
@@ -84,23 +94,23 @@ DEBUGEOF
     fi
     PID=$!
 
-    while [[ $TIMEOUT -gt 0 ]]
+    while [[ ${TIMEOUT} -gt 0 ]]
     do
-      /usr/bin/ps -p $PID > /dev/null 2>&1
+      /usr/bin/ps -p "${PID}" > /dev/null 2>&1
       if [[ $? -ne 0 ]]
       then
         break
       fi
-      TIMEOUT=$(($TIMEOUT - 1))
+      TIMEOUT=$(( TIMEOUT - 1 ))
       sleep 1
     done
 
 # if the timeout reaches 0, then the process was killed.
 
-    if [[ $TIMEOUT -le 0 ]]
+    if [[ ${TIMEOUT} -le 0 ]]
     then
-      kill -KILL $PID
-      echo "ERROR: $CONTENT process killed" >> $LOG
+      kill -KILL "${PID}"
+      echo "ERROR: ${CONTENT} process killed" >> "${LOG}"
     fi
   fi
 done
