Updated to fix variables and a few errors

diff --git a/bin/chketh b/bin/chketh
--- a/bin/chketh
+++ b/bin/chketh
@@ -4,32 +4,41 @@
 # Capture the current network settings; up, link speed, etc
 # modify the script to check for, and kill the dladm or ethtool process if it's taking too long
 
-PROGNAME="chketh"
+#BASENAME=$(basename "${0}")
+DIRNAME=$(dirname "${0}")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
 CONTENT="chketh"
 TIMEOUT=40
-OS=`uname`
-INTRADO=/opt/intrado
-LOG=$INTRADO/log/intrado.log
+LOG=${SCRIPTS_LOGS}/intrado.log
 
-if [[ -f $INTRADO/etc/$CONTENT.output ]]
+if [[ -f ${SCRIPTS_LOGS}/${CONTENT}.output ]]
 then
-  rm $INTRADO/etc/$CONTENT.output
+  rm "${SCRIPTS_LOGS}/${CONTENT}.output"
 fi
 
 # the process for checking the interfaces on a Sun system
 if [[ $OS = "SunOS" ]]
 then
-  /usr/sbin/dladm show-dev > $INTRADO/etc/chketh.output
+  /usr/sbin/dladm show-dev > "${SCRIPTS_LOGS}/${CONTENT}.output"
   PID=$!
 
   while [[ $TIMEOUT -gt 0 ]]
   do
-    /usr/bin/ps -p $PID > /dev/null 2>&1
+    /usr/bin/ps -p "${PID}" > /dev/null 2>&1
     if [[ $? -ne 0 ]]
     then
       break
     fi
-    TIMEOUT=$(($TIMEOUT - 1))
+    TIMEOUT=$(( $TIMEOUT - 1 ))
     sleep 1
   done
 
@@ -37,8 +46,8 @@ then
 
   if [[ $TIMEOUT -le 0 ]]
   then
-    kill -KILL $PID
-    echo "ERROR: $CONTENT process killed" >> $LOG
+    kill -KILL "${PID}"
+    echo "ERROR: $CONTENT process killed" >> "${LOG}"
   fi
 fi
 
@@ -46,21 +55,21 @@ fi
 # the process for checking the interfaces on a Linux system
 if [[ $OS = "Linux" ]]
 then
-  for i in `ls /etc/sysconfig/network-scripts/ifcfg*`
+  for i in $(ls /etc/sysconfig/network-scripts/ifcfg*)
   do
-    IF=`echo $i | cut -f3 -d\-`
+    IF=$(echo "${i}" | cut -f3 -d\-)
 
-    /sbin/ethtool $IF >> $INTRADO/etc/chketh.output
+    /sbin/ethtool "${IF}" >> "${SCRIPTS_LOGS}/${CONTENT}.output"
     PID=$!
 
     while [[ $TIMEOUT -gt 0 ]]
     do
-      /usr/bin/ps -p $PID > /dev/null 2>&1
+      /usr/bin/ps -p "${PID}" > /dev/null 2>&1
       if [[ $? -ne 0 ]]
       then
         break
       fi
-      TIMEOUT=$(($TIMEOUT - 1))
+      TIMEOUT=$(( $TIMEOUT - 1 ))
       sleep 1
     done
 
@@ -68,8 +77,8 @@ then
 
     if [[ $TIMEOUT -le 0 ]]
     then
-      kill -KILL $PID
-      echo "ERROR: $CONTENT process killed" >> $LOG
+      kill -KILL "${PID}"
+      echo "ERROR: $CONTENT process killed" >> "${LOG}"
     fi
   done
 fi
