Updated to add config and fix variables

diff --git a/bin/chkghost b/bin/chkghost
--- a/bin/chkghost
+++ b/bin/chkghost
@@ -5,16 +5,27 @@
 # This script checks for the existance of glibc-2.18 or higher
 # if older than 2.18, vulnerable to ghost
 
-INTRADO=/opt/intrado
-OUT=$INTRADO/etc/ghost.output
-CVE=$INTRADO/etc/ghost.cve
-BIN=$INTRADO/bin
+#BASENAME=$(basename "${0}")
+DIRNAME=$(dirname "${0}")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
+OUT=${SCRIPTS_LOGS}/ghost.output
+CVE=${SCRIPTS_LOGS}/ghost.cve
+BIN=${SCRIPTS_BINS}
 MONTH=`date | awk '{print $2}'`
 OS=`uname`
 
 if [[ $OS = 'Linux' ]]
 then
-  rpm -qa | grep glibc-2 > $OUT
-  rpm -q --changelog glibc | grep -i cve > $INTRADO/etc/ghost.cve
+  rpm -qa | grep glibc-2 > ${OUT}
+  rpm -q --changelog glibc | grep -i cve > ${CVE}/ghost.cve
 fi
 
diff --git a/bin/chkmachinfo b/bin/chkmachinfo
--- a/bin/chkmachinfo
+++ b/bin/chkmachinfo
@@ -2,9 +2,20 @@
 
 # Run the machinfo utility to get a snapshot of HP-UX hardware details
 
-OS=`uname`
+#BASENAME=$(basename "${0}")
+DIRNAME=$(dirname "${0}")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
 INTRADO='/opt/intrado'
-ID=`id | cut -f1 -d\( | cut -f2 -d=`
+ID=$(id | cut -f1 -d\( | cut -f2 -d=)
 
 if [[ ! $ID = 0 ]]
 then
@@ -12,18 +23,18 @@ then
   exit 1
 fi
 
-if [[ -f $INTRADO/etc/machinfo.output ]]
+if [[ -f ${SCRIPTS_LOGS}/machinfo.output ]]
 then
-  rm $INTRADO/etc/machinfo.output
+  rm ${SCRIPTS_LOGS}/machinfo.output
 fi
 
 if [[ $OS = "HP-UX" ]]
 then
   if [[ -f /usr/contrib/bin/machinfo ]]
   then
-    /usr/contrib/bin/machinfo > $INTRADO/etc/machinfo.output 2>&1
+    /usr/contrib/bin/machinfo > ${SCRIPTS_LOGS}/machinfo.output 2>&1
   else
-    echo "Unable to locate machinfo" > $INTRADO/etc/machinfo.output
+    echo "Unable to locate machinfo" > ${SCRIPTS_LOGS}/machinfo.output
   fi
 fi
 
diff --git a/bin/chkpackages b/bin/chkpackages
--- a/bin/chkpackages
+++ b/bin/chkpackages
@@ -3,10 +3,20 @@
 # Carl Schelin
 # Generate a list of packages for import into the inventory
 
-OS=$(uname)
-INTRADO='/opt/intrado'
+#BASENAME=$(basename "${0}")
+DIRNAME=$(dirname "${0}")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
 ID=$(id | cut -f1 -d\( | cut -f2 -d=)
-OUTPUT=$INTRADO/etc/chkpackages.output
+OUTPUT=${SCRIPTS_LOGS}/chkpackages.output
 
 if [[ ! $ID = 0 ]]
 then
