Updated to include config file and fix variavbles

diff --git a/bin/chkpwck b/bin/chkpwck
--- a/bin/chkpwck
+++ b/bin/chkpwck
@@ -2,9 +2,19 @@
 
 # Run the pwck utility to validate the /etc/passwd and /etc/shadow files
 
-OS=`uname`
-INTRADO='/opt/intrado'
-ID=`id | cut -f1 -d\( | cut -f2 -d=`
+#BASENAME=$(basename "${0}")
+DIRNAME=$(dirname "${0}")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
+ID=$(id | cut -f1 -d\( | cut -f2 -d=)
 
 if [[ ! $ID = 0 ]]
 then
@@ -12,29 +22,29 @@ then
   exit 1
 fi
 
-if [[ -f $INTRADO/etc/pwck.output ]]
+if [[ -f ${SCRIPTS_LOGS}/pwck.output ]]
 then
-  rm $INTRADO/etc/pwck.output
+  rm "${SCRIPTS_LOGS}/pwck.output"
 fi
 
 # create a blank file to stop the complaining of the morning report
-touch $INTRADO/etc/pwck.output
+touch "${SCRIPTS_LOGS}/pwck.output"
 
 if [[ $OS = "Linux" ]]
 then
-  /usr/sbin/pwck > $INTRADO/etc/pwck.output 2>&1
+  /usr/sbin/pwck > "${SCRIPTS_LOGS}/pwck.output" 2>&1
 fi
 if [[ $OS = "SunOS" ]]
 then
-  /usr/sbin/pwck > $INTRADO/etc/pwck.output 2>&1
+  /usr/sbin/pwck > "${SCRIPTS_LOGS}/pwck.output" 2>&1
 fi
 if [[ $OS = "HP-UX" ]]
 then
-  /usr/sbin/pwck > $INTRADO/etc/pwck.output 2>&1
+  /usr/sbin/pwck > "${SCRIPTS_LOGS}/pwck.output" 2>&1
 fi
 if [[ $OS = "OSF1" ]]
 then
-  /usr/sbin/pwck > $INTRADO/etc/pwck.output 2>&1
+  /usr/sbin/pwck > "${SCRIPTS_LOGS}/pwck.output" 2>&1
 fi
 
 exit 0
