added config and fixed variables

diff --git a/bin/chkpolicy b/bin/chkpolicy
--- a/bin/chkpolicy
+++ b/bin/chkpolicy
@@ -4,15 +4,26 @@
 # Carl Schelin
 # Checks the openview installed policies
 
-ADMIN=/opt/intrado/
+#BASENAME=$(basename "${0}")
+DIRNAME=$(dirname "${0}")
 
-if [[ -f $ADMIN/etc/opcpolicy.output ]]
+if [[ ! -f ${DIRNAME}/../.config ]]
 then
-  rm $ADMIN/etc/chkpolicy.output
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
+# delete the old file in case OV is removed so we don't have old stuff hanging around
+if [[ -f ${SCRIPTS_LOGS}/opcpolicy.output ]]
+then
+  rm ${SCRIPTS_LOGS}/chkpolicy.output
 fi
 
 if [[ -f /opt/OV/bin/ovpolicy ]]
 then
-  /opt/OV/bin/ovpolicy -list > $ADMIN/etc/chkpolicy.output
+  /opt/OV/bin/ovpolicy -list > ${SCRIPTS_LOGS}/chkpolicy.output
 fi
 
