Updated to add config and fix variables

diff --git a/bin/chkports b/bin/chkports
--- a/bin/chkports
+++ b/bin/chkports
@@ -1,12 +1,23 @@
 #!/bin/ksh
 
-LSOF=''
-OS=`uname`
-
 # possible solution to x86 Solaris; need newer lsof for new data structures, but in the mean time, something like this works as well:
 # pfiles 152 | grep sockname | grep AF_INET | grep -v "port: 0" | awk '{print $NF}' | sort | uniq
 # where 152 is returned from lsof when looking for TCP but getting:
 # no TCP/UDP/IP information available
+
+#BASENAME=$(basename "${0}")
+DIRNAME=$(dirname "${0}")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
+LSOF=''
 
 if [[ -f /usr/bin/lsof ]]
 then
@@ -28,7 +39,7 @@ then
   LSOF=/usr/sbin/lsof
 fi
 
-LOG=/opt/intrado/etc/chkports.output
+LOG=${SCRIPTS_LOGS}/chkports.output
 if [[ -f $LOG ]]
 then
   rm $LOG
@@ -42,33 +53,33 @@ fi
 if [[ $OS = "HP-UX" ]]
 then
   PORTS=`netstat -an | grep LISTEN | awk '{print $4}' | awk -F. '{print $NF}' | sort -n`
-  $LSOF -P -n | egrep "(TCP|UDP)" | grep LISTEN | awk '{print $1":"$3":"$9}' | sort | uniq > /opt/intrado/var/lsof.output
+  $LSOF -P -n | egrep "(TCP|UDP)" | grep LISTEN | awk '{print $1":"$3":"$9}' | sort | uniq > ${SCRIPTS_LOGS}/lsof.output
 fi
 
 if [[ $OS = "Linux" ]]
 then
   PORTS=`netstat -an | grep "LISTEN " | awk '{print $4}' | awk -F: '{print $NF}' | sort -n`
-  $LSOF -P -n | egrep "(TCP|UDP)" | grep LISTEN | awk '{print $1":"$3":"$8}' | grep -v "TCP" | sort | uniq > /opt/intrado/var/lsof.output
+  $LSOF -P -n | egrep "(TCP|UDP)" | grep LISTEN | awk '{print $1":"$3":"$8}' | grep -v "TCP" | sort | uniq > ${SCRIPTS_LOGS}/lsof.output
 # lsof on Ubuntu has a different number of columns
-  if [[ ! -s /opt/intrado/var/lsof.output ]]
+  if [[ ! -s ${SCRIPTS_LOGS}/lsof.output ]]
   then
-    $LSOF -P -n | egrep "(TCP|UDP)" | grep LISTEN | awk '{print $1":"$3":"$9}' | sort | uniq > /opt/intrado/var/lsof.output
+    $LSOF -P -n | egrep "(TCP|UDP)" | grep LISTEN | awk '{print $1":"$3":"$9}' | sort | uniq > ${SCRIPTS_LOGS}/lsof.output
   fi
 fi
 
 if [[ $OS = "OSF1" ]]
 then
   PORTS=`netstat -an | grep LISTEN | awk '{print $4}' | awk -F. '{print $NF}' | sort -n`
-  $LSOF -P -n | egrep "(TCP|UDP)" | grep LISTEN | awk '{print $1":"$3":"$9}' | sort | uniq > /opt/intrado/var/lsof.output
+  $LSOF -P -n | egrep "(TCP|UDP)" | grep LISTEN | awk '{print $1":"$3":"$9}' | sort | uniq > ${SCRIPTS_LOGS}/lsof.output
 fi
 
 if [[ $OS = "SunOS" ]]
 then
   PORTS=`netstat -an | grep LISTEN | awk '{print $1}' | awk -F. '{print $NF}' | sort -n`
-  $LSOF -P -n | egrep "(TCP|UDP)" | grep LISTEN | awk '{print $1":"$3":"$9}' | sort | uniq > /opt/intrado/var/lsof.output
+  $LSOF -P -n | egrep "(TCP|UDP)" | grep LISTEN | awk '{print $1":"$3":"$9}' | sort | uniq > ${SCRIPTS_LOGS}/lsof.output
 
 # special setup for x86 sun boxes
-  if [[ ! -s /opt/intrado/var/lsof.output ]]
+  if [[ ! -s ${SCRIPTS_LOGS}/lsof.output ]]
   then
     for i in `lsof -P -n | egrep "(TCP|UDP)" | awk '{print $1":"$2":"$3}' | sort | uniq`
     do
@@ -78,7 +89,7 @@ then
 
       for j in `pfiles $PID | grep sockname | grep AF_INET | grep -v "port: 0" | awk '{print $NF}'`
       do
-        echo "$PGM:$OWN:blank:$j" >> /opt/intrado/var/lsof.output
+        echo "$PGM:$OWN:blank:$j" >> ${SCRIPTS_LOGS}/lsof.output
       done
     done
   fi
@@ -86,7 +97,7 @@ fi
 
 for i in $PORTS
 do
-  OUTPUT=`grep ":$i$" /opt/intrado/var/lsof.output`
+  OUTPUT=`grep ":$i$" ${SCRIPTS_LOGS}/lsof.output`
 
   PROGRAM=`echo $OUTPUT | cut -f1 -d:`
   PARENT=`echo $OUTPUT | cut -f2 -d:`
@@ -98,8 +109,8 @@ do
 
 done
 
-if [[ -f /opt/intrado/var/lsof.output ]]
+if [[ -f ${SCRIPTS_LOGS}/lsof.output ]]
 then
-  rm /opt/intrado/var/lsof.output
+  rm ${SCRIPTS_LOGS}/lsof.output
 fi
 
