Updated to add user doesn't exist error

diff --git a/bin/chkserver b/bin/chkserver
--- a/bin/chkserver
+++ b/bin/chkserver
@@ -45,6 +45,7 @@
 # 2017/07/11 - CS - updated to ping servers before checking functionality
 # 2017/07/13 - CS - Add check of the route table. Just parrot the routetable.output file
 # 2017/07/17 - CS - Backup check
+# 2017/07/19 - CS - Added user doesn't exist error for users who may not be in the right group
 
 PROGNAME="chkserver"
 COUNT=0
@@ -298,10 +299,15 @@ then
 # found the group in the group.master file. Now check all users in group.master list against /etc/group list and throw an error if not found
       for j in `grep "^${i}:" $INTRADO/etc/group.master | cut -f2 -d: | sed -e "s/,/ /g"`
       do
-        egrep -qi "^${i}:.*(:|,)${j}(,|$)" /etc/group
+        egrep -qi "^${j}:" /etc/passwd
         if [[ $? = 1 ]]
         then
-          echo -e "    ${RED}${j} was not found in the ${i} group in /etc/group${RESET}" >> $LOG
+          echo -e "    ${RED}${j} does not have a login on this system${RESET}" >> $LOG
+          egrep -qi "^${i}:.*(:|,)${j}(,|$)" /etc/group
+          if [[ $? = 1 ]]
+          then
+            echo -e "    ${RED}${j} was not found in the ${i} group in /etc/group${RESET}" >> $LOG
+          fi
         fi
       done
 # now check all users in /etc/group against group.master and throw an error if found
