Updated to add docs updated to fix dns lookup via dig fixed a typo: erep added a sysadmin variable

diff --git a/bin/chkserver b/bin/chkserver
--- a/bin/chkserver
+++ b/bin/chkserver
@@ -146,6 +146,7 @@
 # 2018/02/19 - CS - Updated the check_route function to check HP-UX route configurations.
 # 2018/02/21 - CS - Added check of 'Enabled' services
 # 2018/02/23 - CS - Updated the check_resolv function to try and resolve this hostname and IP
+# 2018/02/26 - CS - Added doc information to functions.
 
 BASENAME=`basename $0`
 DIRNAME=`dirname $0`
@@ -159,7 +160,7 @@ fi
 # Source the configuration file
 . ${DIRNAME}/../.config
 
-VERSION="${BASENAME} v1.206"
+VERSION="${BASENAME} v1.207"
 COUNT=0
 GATEWAY=''
 GWFLAG='no'
@@ -380,8 +381,13 @@ check_management_route() {
 
 
 ######################
-### Check to make sure employees haven't departed (accounts need to be locked)
-### Number of Checks: [Number of users on the system]
+### Doc: Function: check_active_employees() - (number of users) * 3 Checks
+### Doc: * Using the chksudo.dat file, loops through the /etc/passwd file
+### Doc: ** If the user is not in the users.exclude file (consists of service and system accounts)
+### Doc: ** Checks to see if the user account is locked.
+### Doc: ** If the account is not locked, retrieve the email address from the GECOS field
+### Doc: ** If the email address is _not_ in the intrado.email file
+### Doc: ** Report it as an error (missing user is not locked).
 ######################
 
 check_active_employees() {
@@ -463,8 +469,15 @@ check_active_employees() {
 
 
 ######################
-### Check assigned IP addresses
-### Number of Checks: 4 * [Number of interfaces] + 1
+### Doc: Function: check_addresses() - 6 Checks
+### Doc: * Check to make sure interface starts on boot
+### Doc: * Check the IP Address to make sure it's in /etc/hosts
+### Doc: * Note: Unix uses 192.168.0.0/24 for Private Networks.
+### Doc: ** Check the supplied gateway to see if the interface is on a private network
+### Doc: ** Ignore if private
+### Doc: ** Try to ping the gateway to ensure the interface is up if not private.
+### Doc: * See if the gateway is the default gateway (in /etc/sysconfig/netowrk)
+### Doc: * See if the gateway is configured in the interface file (/etc/sysconfig/network-scripts/ifcfg-xxx)
 ######################
 
 check_addresses() {
@@ -495,7 +508,7 @@ check_addresses() {
     PRIVATE=`ipcalc -n ${FIELD4}/24 | cut -f2 -d=`
     if [[ ${PRIVATE} = '192.168.0.0' ]]
     then
-    printf "%b\n" "    ${GREEN}Gateway ${FIELD4} is on a Private network${RESET}" >> $LOG
+      printf "%b\n" "    ${GREEN}Gateway ${FIELD4} is on a Private network${RESET}" >> $LOG
     else
       echo "  ping check of the gateway: ${FIELD4}"
       ping ${FIELD4} ${PINGCT} > /dev/null
@@ -527,8 +540,10 @@ check_addresses() {
 
 
 ######################
-### Check Centrify if installed
-### Number of Checks: 3
+### Doc: Function: check_centrify() - 
+### Doc: * Checks to see if Centrify is installed
+### Doc: * Checks to see if Centrify is running
+### Doc: * Checks to see if Centrify is connected to a domain and reports which domain
 ######################
 
 check_centrify() {
@@ -583,8 +598,9 @@ check_centrify() {
 
 
 ######################
-### Check the status of cfg2html
-### Number of Checks: 2
+### Doc: Function: check_cfg2html() - 
+### Doc: * Is cfg2html installed
+### Doc: * Has it be run at least once
 ######################
 
 check_cfg2html() {
@@ -609,8 +625,8 @@ check_cfg2html() {
 
 
 ######################
-### Check the number of CPUs against what's requested
-### Number of Checks: 1
+### Doc: Function: check_cpus() - 
+### Doc: * Checks the number of CPUs against the expected number from the chkserver.input file.
 ######################
 
 check_cpus() {
@@ -629,8 +645,8 @@ check_cpus() {
 
 
 ######################
-### Check the to see if there are any crash dump files
-### Number of Checks: 1
+### Doc: Function: check_crash() - 
+### Doc: * Depending on OS, checks the crash dump directory for any files.
 ######################
 
 check_crash() {
@@ -666,8 +682,11 @@ check_crash() {
 
 
 ######################
-### Check Data Palette if installed
-### Number of Checks: 3
+### Doc: Function: check_data_palette() - 
+### Doc: * Checks to see if Data Palette is installed
+### Doc: * Checks to see if Data Palette is running
+### Doc: * Checks to see if Data Palette can ping the Nerve Center(s)
+### Doc: * Checks to see if Data Palette can access the Nerve Center(s)
 ######################
 
 check_data_palette() {
@@ -727,8 +746,8 @@ check_data_palette() {
 
 
 ######################
-### Check default installation passwords
-### Number of Checks: 2 + [Number of Sysadmins]
+### Doc: Function: check_default_passwords() - 
+### Doc: * Depending on OS, checks each system admin to see if the installation password is still set to the default
 ######################
 
 check_default_passwords() {
@@ -739,7 +758,7 @@ check_default_passwords() {
     echo "Entering check_default_passwords(4)"
   fi
   printf "%b\n" "  ${GREEN}Account password verification${RESET}" >> $LOG
-  for j in root cschelin kzupan jnoyes tcooper escott mchahud jschroet jmetz ppietras unixsvc
+  for j in root ${SYSADMINS}
   do
     UNIXDEF='$1$YDorwFsD$0/fIFtn7YZhMvZjAUZ.V./'
 
@@ -776,8 +795,10 @@ check_default_passwords() {
 
 
 ######################
-### Check disk space
-### Number of Checks: 2
+### Doc: Function: check_disk_space() - 
+### Doc: Depending on the OS, checks the disk space for standard file systems
+### Doc: Reports a warning if over 85%
+### Doc: Reports an error if over 95%
 ######################
 
 check_disk_space() {
@@ -830,8 +851,9 @@ check_disk_space() {
 
 
 ######################
-### Check the health of Solaris Disk Suite
-### Number of Checks: 2
+### Doc: Function: check_disk_suite() - 
+### Doc: * Checks for capital letters in the output of metadb indicating a failed disk
+### Doc: * Checks for the word 'metareplace' metastat indicating a failed disk
 ######################
 
 check_disk_suite() {
@@ -864,8 +886,8 @@ check_disk_suite() {
 
 
 ######################
-### Make sure Sun box can auto start on boot
-### Number of Checks: 2
+### Doc: Function: check_eeprom() - 
+### Doc: * Checks the output of eeprom on Solaris for the auto-boot? setting. False == the system won't boot to the OS
 ######################
 
 check_eeprom() {
@@ -893,8 +915,9 @@ check_eeprom() {
 
 
 ######################
-### Check access to the mail server
-### Number of Checks: 2
+### Doc: Function: check_email() - 
+### Doc: * Checks to see if the email server(s) can be pinged
+### Doc: * Checks to see if the email server(s) can be accessed
 ######################
 
 check_email() {
@@ -944,8 +967,8 @@ check_email() {
 
 
 ######################
-### Check virtual machines for a floppy drive; shouldn't be there
-### Number of Checks: 1
+### Doc: Function: check_floppy() - 
+### Doc: * Only for VMware systems, check to see if the Floppy device exists.
 ######################
 
 check_floppy() {
@@ -972,8 +995,14 @@ check_floppy() {
 
 
 ######################
-### Check group memberships
-### Number of Checks: 5 * [Number of users on the system]
+### Doc: Function: check_group_membership() - 
+### Doc: * Collects all the groups from the system and from any external groups (Centrify)
+### Doc: * Loops through the group listing on the system and checks the group against the group.master file.
+### Doc: ** Reports if a group is not standard (webadmins vs standard webapps for example)
+### Doc: * Loops through the group.master list of users for the found group
+### Doc: ** reports if a user should and doesn't have an account on the system
+### Doc: ** reports if a user should be a member of the system group and is not
+### Doc: * Loops through the user list for the system group and reports if the user isn't in the group.master file
 ######################
 
 # todo: check for centrify to be installed
@@ -1109,7 +1138,7 @@ check_group_membership() {
 
 
 ######################
-### Check the hostname
+### Doc: Function: check_hostname() - 
 ### Number of Checks: 1
 ######################
 
@@ -1130,7 +1159,7 @@ check_hostname() {
 
 
 ######################
-### Check interfaces for status
+### Doc: Function: check_interfaces() - 
 ### Number of Checks: 1
 ######################
 
@@ -1173,7 +1202,7 @@ check_interfaces() {
 
 
 ######################
-### Check to make sure scripts have run
+### Doc: Function: check_intrado() - 
 ### Number of Checks: 2
 ######################
 
@@ -1199,7 +1228,7 @@ check_intrado() {
 
 
 ######################
-### Check access to the Jumpstart web site
+### Doc: Function: check_jumpstart() - 
 ### Number of Checks: 2
 ######################
 
@@ -1250,7 +1279,7 @@ check_jumpstart() {
 
 
 ######################
-### Check to make sure ksh is linked. On RH7, ksh is in /bin vs /usr/bin as it is on every other system.
+### Doc: Function: check_ksh() - 
 ### Number of Checks: 1
 ######################
 
@@ -1274,7 +1303,7 @@ check_ksh() {
 
 
 ######################
-### Check the status of running pods
+### Doc: Function: check_kubernetes() - 
 ### Number of Checks: 2 * [Number of Containers to check]
 ######################
 
@@ -1348,7 +1377,7 @@ check_kubernetes() {
 
 
 ######################
-### Check to make sure logging is current (_something_ with today's date in the logs)
+### Doc: Function: check_logs() - 
 ### Number of Checks: 1
 ######################
 
@@ -1389,7 +1418,7 @@ check_logs() {
 
 
 ######################
-### Check for deleted items indicating a lost log file typically
+### Doc: Function: check_lsof() - 
 ### Number of Checks: 1
 ######################
 
@@ -1415,7 +1444,7 @@ check_lsof() {
 
 
 ######################
-### Check the system memory
+### Doc: Function: check_memory() - 
 ### Number of Checks: 2
 ######################
 
@@ -1467,7 +1496,7 @@ check_memory() {
 
 
 ######################
-### Check the status of Netbackup
+### Doc: Function: check_netbackup() - 
 ### Number of Checks: 10
 ######################
 
@@ -1604,6 +1633,7 @@ check_netbackup() {
 
 
 ######################
+### Doc: Function: check_nrpe() - 
 ### Check the status of Nagios Remote Plugin Executor
 ### Number of Checks: 2
 ######################
@@ -1632,7 +1662,7 @@ check_nrpe() {
 
 
 ######################
-### Check to see if there are any out of memory killer messages (oom-killer)
+### Doc: Function: check_oomkiller() - 
 ### Number of Checks: 1
 ######################
 
@@ -1655,7 +1685,7 @@ check_oomkiller() {
 
 
 ######################
-### Check the status of Openview
+### Doc: Function: check_openview() - 
 ### Number of Checks: 9
 ######################
 
@@ -1833,7 +1863,7 @@ check_openview() {
 
 
 ######################
-### Check Opnet if found
+### Doc: Function: check_opnet() - 
 ### Number of Checks: 6
 ######################
 
@@ -1903,7 +1933,7 @@ check_opnet() {
 
 
 ######################
-### Check to see if users who have privileged access have expired or shouldn't have it
+### Doc: Function: check_privileged_access() - 
 ### Number of Checks: 2 * [Number of users on the system]
 ######################
 
@@ -1968,7 +1998,7 @@ check_privileged_access() {
 
 
 ######################
-### Check the status of subscriptions for Red Hat servers only (so not an OS check)
+### Doc: Function: check_redhat_subscription() - 
 ### Number of Checks: 1
 ######################
 
@@ -2079,7 +2109,7 @@ check_redhat_subscription() {
 
 
 ######################
-### Check the status of RemoveIPS on Red Hat systems
+### Doc: Function: check_removeips() - 
 ### Number of Checks: 2
 ######################
 
@@ -2119,7 +2149,7 @@ check_removeips() {
 
 
 ######################
-### Check the resolv.conf nameserver entries
+### Doc: Function: check_resolver() - 
 ### Number of Checks: 2 * [Number of nameserver entries] + 1
 ######################
 
@@ -2178,13 +2208,13 @@ check_resolver() {
 
 # see if FQDN is in DNS
 # see if PTR for FQDN is in DNS
-          HOSTA=`dig ${FQDN} | grep "^${FQDN}" | awk '{print $NF}'`
+          HOSTA=`dig ${FQDN} | grep -v ";" | grep "^${FQDN}" | awk '{print $NF}'`
           if [[ -z ${HOSTA} ]]
           then
             printf "%b\n" "    ${RED}${FQDN} unable to be found in DNS.${RESET} dig ${FQDN}" >> $LOG
           else
 # dig isn't working
-            HOSTPTR=`dig -x ${HOSTA} | grep -v ";" | erep "in-addr.arpa" | awk '{print $NF}'`
+            HOSTPTR=`dig -x ${HOSTA} | grep -v ";" | grep "in-addr.arpa" | awk '{print $NF}'`
             if [[ -z ${HOSTPTR} ]]
             then
               printf "%b\n" "    ${RED}${HOSTA} unable to be found in DNS.${RESET} dig -x ${HOSTA}" >> $LOG
@@ -2213,7 +2243,7 @@ check_resolver() {
 
 
 ######################
-### Check the status of the routing tables
+### Doc: Function: check_routetable() - 
 ### Number of Checks: 1
 ######################
 
@@ -2266,7 +2296,7 @@ check_routetable() {
 
 
 ######################
-### Check the status of rrdtool; should be running on Linux and Sun systems
+### Doc: Function: check_rrdtool() - 
 ### Number of Checks: 1
 ######################
 
@@ -2291,7 +2321,7 @@ check_rrdtool() {
 
 
 ######################
-### Check remote root access via ssh
+### Doc: Function: check_security() - 
 ### Number of Checks: 1
 ######################
 
@@ -2316,7 +2346,7 @@ check_security() {
 
 
 ######################
-### Check the status of selinux. Should be disabled. If enabled, permissive is warning, enforcing is error
+### Doc: Function: check_selinux() - 
 ### Number of Checks: 1
 ######################
 
@@ -2356,7 +2386,7 @@ check_selinux() {
 
 
 ######################
-### Check the sudoers file
+### Doc: Function: check_sudoers() - 
 ### Number of Checks: 3
 ######################
 
@@ -2422,7 +2452,7 @@ check_sudoers() {
 
 
 ######################
-### Check to make sure swap is appropriatly sized
+### Doc: Function: check_swap() - 
 ### Number of Checks: 3
 ### For Red Hat:
 ### Swap >= Ram up to 8G
@@ -2486,7 +2516,7 @@ check_swap() {
 
 
 ######################
-### Check to see if the /opt/techops[70] directory exists
+### Doc: Function: check_techops() - 
 ### Number of Checks: 2
 ######################
 
@@ -2513,7 +2543,7 @@ check_techops() {
 
 
 ######################
-### Check the time sources
+### Doc: Function: check_time() - 
 ### Number of Checks: 6
 ######################
 
@@ -2656,7 +2686,7 @@ check_time() {
 
 
 ######################
-### Check the vmware agent
+### Doc: Function: check_vmware_agent() - 
 ### Number of Checks: 2
 ######################
 
@@ -2720,11 +2750,16 @@ check_vmware_agent() {
   fi
 }
 
+# show documentation for the script
+if [[ ! -z $1 ]] && [[ "$1" = '-h' ]]
+then
+  grep "### Doc: " $0 | grep -v grep | sed -e "s/### Doc: //g" | sed -e "s/^Function:/\nFunction:/g"
+  exit 1
+fi
+
 ######################
 ### End of Functions
 ######################
-
-
 
 echo "" > $LOG
 echo "================================" >> $LOG
