Updated for HP-UX to be able to parse out the APA information and provide valid date to be imported into the inventory

diff --git a/bin/chksys b/bin/chksys
--- a/bin/chksys
+++ b/bin/chksys
@@ -598,29 +598,31 @@ function network_iface {
 # and /etc/lanmon/lanconfig.ascii
 
 # output is 'server,network,interface,IP,ip6?,netmask,mac,groupname,gateway,defaultgw?,parent'
-    GROUP=''
-    IP6=0
-    for i in `/usr/sbin/nwmgr | /usr/bin/awk '/ UP /{print $1":"$3":"$6}'`
-    do
-      INTERFACE=`echo $i | cut -f1 -d:`
-      PARENT=`echo $i | cut -f3 -d:`
-      # converting 0x123456789ABC to 12:34:56:78:9A:BC
-      MAC=`echo $i | awk -F: '{ printf "%s:%s:%s:%s:%s:%s",
-                                         substr($2,3,2),
-                                         substr($2,5,2),
-                                         substr($2,7,2),
-                                         substr($2,9,2),
-                                         substr($2,11,2),
-                                         substr($2,13,2)}'`
+    if [[ -f /usr/sbin/nwmgr ]]
+    then
+      GROUP=''
+      IP6=0
+      for i in `/usr/sbin/nwmgr | /usr/bin/awk '/ UP /{print $1":"$3":"$6}'`
+      do
+        INTERFACE=`echo $i | cut -f1 -d:`
+        PARENT=`echo $i | cut -f3 -d:`
+        # converting 0x123456789ABC to 12:34:56:78:9A:BC
+        MAC=`echo $i | awk -F: '{ printf "%s:%s:%s:%s:%s:%s",
+                                           substr($2,3,2),
+                                           substr($2,5,2),
+                                           substr($2,7,2),
+                                           substr($2,9,2),
+                                           substr($2,11,2),
+                                           substr($2,13,2)}'`
 # we have to get IP information from the netconf file if it returns 'no such interface'.
 # Otherewise it's an apa interface and we can get it from ifconfig (or hp_apaconf)
-      ISTATUS=`/usr/sbin/ifconfig $INTERFACE 2>&1 | grep -v 'no such interface'`
-      if [[ -n $ISTATUS ]]
-      then
-        IP=`ifconfig $INTERFACE 2>1 | awk '/inet /{print $2}'`
-        MASK=`ifconfig $INTERFACE 2>1 | awk '/ netmask /{print $4}'`
-        NETMASK=`printf "%d.%d.%d.%d\n" $(echo "$MASK"| sed 's/../0x& /g')`
-      else
+        ISTATUS=`/usr/sbin/ifconfig $INTERFACE 2>&1 | grep -v 'no such interface'`
+        if [[ -n $ISTATUS ]]
+        then
+          IP=`ifconfig $INTERFACE 2>1 | awk '/inet /{print $2}'`
+          MASK=`ifconfig $INTERFACE 2>1 | awk '/ netmask /{print $4}'`
+          NETMASK=`printf "%d.%d.%d.%d\n" $(echo "$MASK"| sed 's/../0x& /g')`
+        else
 # netconf file output
 #INTERFACE_NAME[2]="lan6"
 #IP_ADDRESS[2]="192.168.2.1"
@@ -639,28 +641,165 @@ function network_iface {
 #ROUTE_SOURCE[0]=""
 #ROUTE_SKIP[0]=""
 
-        INSTANCE=`egrep "^INTERFACE_NAME.*${INTERFACE}" /etc/rc.config.d/netconf | cut -f2 -d\[ | cut -f1 -d\]`
-        IP=`egrep "^IP_ADDRESS\[${INSTANCE}\]" /etc/rc.config.d/netconf | tail -1 | cut -f2 -d= | sed -e "s/\"//g"`
-        NETMASK=`egrep "^SUBNET_MASK\[${INSTANCE}\]" /etc/rc.config.d/netconf | tail -1 | cut -f2 -d= | sed -e "s/\"//g"`
-        GATEWAY=`egrep "^ROUTE_GATEWAY\[${INSTANCE}\]" /etc/rc.config.d/netconf | tail -1 | cut -f2 -d= | sed -e "s/\"//g"`
-      fi
-
+          INSTANCE=`egrep "^INTERFACE_NAME.*${INTERFACE}" /etc/rc.config.d/netconf | cut -f2 -d\[ | cut -f1 -d\]`
+          IP=`egrep "^IP_ADDRESS\[${INSTANCE}\]" /etc/rc.config.d/netconf | tail -1 | cut -f2 -d= | sed -e "s/\"//g"`
+          NETMASK=`egrep "^SUBNET_MASK\[${INSTANCE}\]" /etc/rc.config.d/netconf | tail -1 | cut -f2 -d= | sed -e "s/\"//g"`
+          GATEWAY=`egrep "^ROUTE_GATEWAY\[${INSTANCE}\]" /etc/rc.config.d/netconf | tail -1 | cut -f2 -d= | sed -e "s/\"//g"`
+        fi
+  
       # found the default gateway information
-      if [[ $DEFDEV = $INTERFACE ]]; then
-        OUTGATE=${DEFGATE}
-        OUTROUTE=${DEFROUTE}
-      else
+        if [[ $DEFDEV = $INTERFACE ]]; then
+          OUTGATE=${DEFGATE}
+          OUTROUTE=${DEFROUTE}
+        else
 # where to get route information for apa interfaces? from the interface returned above?
-        OUTGATE=${GATEWAY}
-        OUTROUTE=0
-      fi
-      logit "network" "interface" "${INTERFACE},${IP},${IP6},${NETMASK},${MAC},${GROUP},${OUTGATE},${OUTROUTE},${PARENT}"
-    done
+          OUTGATE=${GATEWAY}
+          OUTROUTE=0
+        fi
+        logit "network" "interface" "${INTERFACE},${IP},${IP6},${NETMASK},${MAC},${GROUP},${OUTGATE},${OUTROUTE},${PARENT}"
+      done
+    fi
+
+# loopback interface
     IP=`/usr/sbin/ifconfig lo0 2>1 | /usr/bin/grep 'inet ' | /usr/bin/awk '{print $2}'`
     MASK=`/usr/sbin/ifconfig lo0 2>1 | /usr/bin/grep ' netmask ' | /usr/bin/awk '{print $4}'`
     NETMASK=`printf "%d.%d.%d.%d\n" $(echo "$MASK"| sed 's/../0x& /g')`
     logit "network" "interface" "lo0,${IP},0,${NETMASK},lo0,,,0,"
 
+    if [[ -f /usr/sbin/lanscan ]]
+    then
+
+      if [[ -f /etc/lanmon/lanconfig.ascii ]]
+      then
+        IP6=0
+        for i in `egrep -v "^(#|$)" /etc/lanmon/lanconfig.ascii | egrep "(FAILOVER_GROUP|PRIMARY|STANDBY)" | awk '{print $1":"$2}'`
+        do
+          KEY=`echo $i | cut -f1 -d:`
+          VALUE=`echo $i | cut -f2 -d:`
+          PARENT=''
+
+          if [[ $KEY = 'FAILOVER_GROUP' ]]
+          then
+            MAC=`lanscan | grep $VALUE | awk '{ printf "%s:%s:%s:%s:%s:%s",
+                                         substr($2,3,2),
+                                         substr($2,5,2),
+                                         substr($2,7,2),
+                                         substr($2,9,2),
+                                         substr($2,11,2),
+                                         substr($2,13,2)}`
+	    IP=`ifconfig $VALUE 2>1 | awk '/inet /{print $2}'`
+            MASK=`ifconfig $VALUE 2>1 | awk '/ netmask /{print $4}'`
+            NETMASK=`printf "%d.%d.%d.%d\n" $(echo "$MASK"| sed 's/../0x& /g')`
+            PARENTALUNIT=$VALUE
+          fi
+
+          if [[ $KEY = 'PRIMARY' ]] || [[ $KEY = 'STANDBY' ]]
+          then
+# first, see if it's in the output of lanscan in order to get the MAC
+            LANSCAN=`lanscan | grep $VALUE`
+            MAC=""
+            if [[ ! -z $LANSCAN ]]
+            then
+              MAC=`lanscan | grep $VALUE | '{ printf "%s:%s:%s:%s:%s:%s",
+                                         substr($2,3,2),
+                                         substr($2,5,2),
+                                         substr($2,7,2),
+                                         substr($2,9,2),
+                                         substr($2,11,2),
+                                         substr($2,13,2)}`
+            fi
+
+            ISTATUS=`ifconfig $VALUE 2>1 | grep -v "no such interface"`
+            if [[ ! -z $ISTATUS ]]
+            then
+	      IP=`ifconfig $VALUE 2>1 | awk '/inet /{print $2}'`
+              MASK=`ifconfig $VALUE 2>1 | awk '/ netmask /{print $4}'`
+              NETMASK=`printf "%d.%d.%d.%d\n" $(echo "$MASK"| ed 's/../0x& /g')`
+            else
+              INSTANCE=`egrep "^INTERFACE_NAME.*${VALUE}" /etc/rc.config.d/netconf | cut -f2 -d\[ | cut -f1 -d\]`
+              IP=`egrep "^IP_ADDRESS\[${INSTANCE}\]" /etc/rc.config.d/netconf | tail -1 | cut -f2 -d= | sed -e "s/\"//g"`
+              MASK=`egrep "^SUBNET_MASK\[${INSTANCE}\]" /etc/rc.config.d/netconf | tail -1 | cut -f2 -d= | sed -e "s/\"//g"`
+
+# some are 0xffff, some are 255.255.255
+              echo $MASK | grep "0x" > /dev/null 2>&1
+              if [[ $? -eq 0 ]]
+              then
+                NETMASK=`printf "%d.%d.%d.%d\n" $(echo "$MASK"| sed -e "s/0x//g" | sed 's/../0x& /g')`
+              else
+                NETMASK=$MASK
+              fi
+
+              GATEWAY=`egrep "^ROUTE_GATEWAY\[${INSTANCE}\]" /etc/rc.config.d/netconf | tail -1 | cut -f2 -d= | sed -e "s/\"//g"`
+              PARENT=$PARENTALUNIT
+            fi
+          fi
+
+      # found the default gateway information
+          if [[ $DEFDEV = $VALUE ]]; then
+            OUTGATE=${DEFGATE}
+            OUTROUTE=${DEFROUTE}
+          else
+# where to get route information for apa interfaces? from the interface returned above?
+            OUTGATE=${GATEWAY}
+            OUTROUTE=0
+          fi
+  
+          logit "network" "interface" "${VALUE},${IP},${IP6},${NETMASK},${MAC},${GROUP},${OUTGATE},${OUTROUTE},${PARENT}"
+
+        done
+      fi
+
+      IP6=0
+      for i in `/usr/sbin/lanscan | egrep -v "^(Hardware|Path|LinkAgg)" | grep -v DOWN | awk '{print $5":"$2}'`
+      do
+        INTERFACE=`echo $i | cut -f1 -d:`
+        # converting 0x123456789ABC to 12:34:56:78:9A:BC
+        MAC=`echo $i | awk -F: '{ printf "%s:%s:%s:%s:%s:%s",
+                                         substr($2,3,2),
+                                         substr($2,5,2),
+                                         substr($2,7,2),
+                                         substr($2,9,2),
+                                         substr($2,11,2),
+                                         substr($2,13,2)}`
+
+# we have to get IP information from the netconf file if it returns 'no such interface'.
+# Otherewise it's an apa interface and we can get it from ifconfig (or hp_apaconf)
+        ISTATUS=`ifconfig $INTERFACE 2>&1 | grep -v "no such interface`
+	if [[ -n $ISTATUS ]]
+	then
+	  IP=`ifconfig $INTERFACE 2>1 | awk '/inet /{print $2}'`
+	  MASK=`ifconfig $INTERFACE 2>1 | awk '/ netmask /{print $4}'`
+          NETMASK=`printf "%d.%d.%d.%d\n" $(echo "$MASK"| sed 's/../0x& /g')`
+        else
+          INSTANCE=`egrep "^INTERFACE_NAME.*${INTERFACE}" /etc/rc.config.d/netconf | cut -f2 -d\[ | cut -f1 -d\]`
+          IP=`egrep "^IP_ADDRESS\[${INSTANCE}\]" /etc/rc.config.d/netconf | tail -1 | cut -f2 -d= | sed -e "s/\"//g"`
+          MASK=`egrep "^SUBNET_MASK\[${INSTANCE}\]" /etc/rc.config.d/netconf | tail -1 | cut -f2 -d= | sed -e "s/\"//g"`
+
+# some are 0xffff, some are 255.255.255
+          echo $MASK | grep "0x" > /dev/null 2>&1
+          if [[ $? -eq 0 ]]
+          then
+            NETMASK=`printf "%d.%d.%d.%d\n" $(echo "$MASK"| sed 's/../0x& /g')`
+          else
+            NETMASK=$MASK
+          fi
+
+          GATEWAY=`egrep "^ROUTE_GATEWAY\[${INSTANCE}\]" /etc/rc.config.d/netconf | tail -1 | cut -f2 -d= | sed -e "s/\"//g"`
+	fi
+
+      # found the default gateway information
+        if [[ $DEFDEV = $INTERFACE ]]; then
+          OUTGATE=${DEFGATE}
+          OUTROUTE=${DEFROUTE}
+        else
+# where to get route information for apa interfaces? from the interface returned above?
+          OUTGATE=${GATEWAY}
+          OUTROUTE=0
+        fi
+
+        logit "network" "interface" "${INTERFACE},${IP},${IP6},${NETMASK},${MAC},${GROUP},${OUTGATE},${OUTROUTE},"
+      done
+    fi
 
 
 #    lanscan | grep UP | while read MYLINE
@@ -671,14 +810,6 @@ function network_iface {
 #        IP=`/usr/sbin/ifconfig $INTERFACE 2>1 | /usr/bin/grep 'inet ' | /usr/bin/awk '{print $2}'`
 #        MASK=`/usr/sbin/ifconfig $INTERFACE 2>1 | /usr/bin/grep ' netmask ' | /usr/bin/awk '{print $4}'`
 #        NETMASK=`printf "%d.%d.%d.%d\n" $(echo "$MASK"| sed 's/../0x& /g')`
-#        # converting 0x123456789ABC to 12:34:56:78:9A:BC
-#        MAC=`echo $MYLINE | awk '{ printf "%s:%s:%s:%s:%s:%s",
-#                                         substr($2,3,2),
-#                                         substr($2,5,2),
-#                                         substr($2,7,2),
-#                                         substr($2,9,2),
-#                                         substr($2,11,2),
-#                                         substr($2,13,2)}`
   ;;
   esac
 }
