Moved some bits around to create check_addresses and check_cpus

diff --git a/bin/chkserver b/bin/chkserver
--- a/bin/chkserver
+++ b/bin/chkserver
@@ -109,8 +109,10 @@
 # 2017/10/02 - CS - Updated check_sudoers to verify group entries in the sudoers file exist on the system
 # 2017/10/02 - CS - Updated check_group to check for a centrify group
 # 2017/10/21 - CS - Fix hosts.allow check to permit spaces
+# 2017/10/21 - CS - Added check_cpus
+# 2017/10/21 - CS - Added check_addresses
 
-echo "chkserver v1.140"
+echo "chkserver v1.141"
 
 PROGNAME="chkserver"
 HOSTNAME=`hostname|cut -f1 -d.`
@@ -320,6 +322,69 @@ check_active_employees() {
 
 
 ######################
+### Check assigned IP addresses
+######################
+
+check_addresses() {
+  if [[ ! ${DEBUG} = 'no' ]]
+  then
+    echo "Entering IP check"
+  fi
+  if [[ $OS = 'Linux' ]]
+  then
+    OUTPUT=`ip addr | grep " ${FIELD3}/"`
+  fi
+  if [[ ! -z $OUTPUT ]]
+  then
+    INTERFACE=`egrep "(\"|)${FIELD3}(\"|)$" /etc/sysconfig/network-scripts/ifcfg-* | cut -f1 -d: | cut -f3 -d-`
+    printf "%b\n" "  ${GREEN}IP $FIELD3 configured as ${INTERFACE}${RESET}" >> $LOG
+    egrep -i "onboot.*yes" /etc/sysconfig/network-scripts/ifcfg-${INTERFACE} > /dev/null
+    if [[ $? = 0 ]]
+    then
+      printf "%b\n" "    ${GREEN}${INTERFACE} is configured to start on boot${RESET}" >> $LOG
+    else
+      printf "%b\n" "    ${RED}${INTERFACE} is not configured to start on boot${RESET}" >> $LOG
+    fi
+    grep -i ${FIELD3} /etc/hosts > /dev/null
+    if [[ $? = 1 ]]
+    then
+      printf "%b\n" "    ${YELLOW}${FIELD3} is not in /etc/hosts${RESET}" >> $LOG
+    fi
+    PRIVATE=`ipcalc -n ${FIELD4}/24 | cut -f2 -d=`
+    if [[ ${PRIVATE} = '192.168.0.0' ]]
+    then
+    printf "%b\n" "    ${GREEN}Gateway ${FIELD4} is on a Private network${RESET}" >> $LOG
+    else
+      echo "  ping check of the gateway: ${FIELD4}"
+      ping ${FIELD4} ${PINGCT} > /dev/null 2>&1
+      if [[ $? = 0 ]]
+      then
+        printf "%b\n" "    ${GREEN}Gateway ${FIELD4} accessible${RESET}" >> $LOG
+      else
+        printf "%b\n" "    ${RED}Gateway ${FIELD4} is not responding to ping${RESET}" >> $LOG
+      fi
+    fi
+    GATEWAY="${GATEWAY} ${FIELD4}"
+    grep "GATEWAY=${FIELD4}" /etc/sysconfig/network > /dev/null
+    if [[ $? = 0 ]]
+    then
+      GWMSG="${GWMSG}    ${GREEN}/etc/sysconfig/network:GATEWAY=${FIELD4} configured${RESET}\n"
+      GWFLAG='yes'
+    fi
+# check the interface file too
+    grep "GATEWAY=${FIELD4}" /etc/sysconfig/network-scripts/ifcfg-${INTERFACE} > /dev/null
+    if [[ $? = 0 ]]
+    then
+      GWMSG="${GWMSG}    ${GREEN}/etc/sysconfig/network-scripts/ifcfg-${INTERFACE}:GATEWAY=${FIELD4} configured${RESET}\n"
+      GWFLAG='yes'
+    fi
+  else
+    printf "%b\n" "  ${RED}Unable to locate ${FIELD3} in ip addr output${RESET}" >> $LOG
+  fi
+}
+
+
+######################
 ### Check Centrify if installed
 ######################
 
@@ -395,6 +460,25 @@ check_cfg2html() {
   if [[ ${DEBUG} = '28' ]]
   then
     echo "Exiting check_cfg2html()"
+  fi
+}
+
+
+######################
+### Check the number of CPUs against what's requested
+######################
+
+check_cpus() {
+  if [[ ! ${DEBUG} = 'no' ]]
+  then
+    echo "Entering CPU check"
+  fi
+  COUNT=`grep -c processor /proc/cpuinfo`
+  if [[ $COUNT -ne $FIELD3 ]]
+  then
+    printf "%b\n" "  ${RED}System shows $COUNT CPUs where expected is $FIELD3 CPUs${RESET}" >> $LOG
+  else
+    printf "%b\n" "  ${GREEN}$COUNT CPUs as expected${RESET}" >> $LOG
   fi
 }
 
@@ -1958,83 +2042,18 @@ then
 
     if [[ $FIELD2 = 'CPU' ]]
     then
-      if [[ ! ${DEBUG} = 'no' ]]
-      then
-        echo "Entering CPU check"
-      fi
-      COUNT=`grep -c processor /proc/cpuinfo`
-      if [[ $COUNT -ne $FIELD3 ]]
-      then
-        printf "%b\n" "  ${RED}System shows $COUNT CPUs where expected is $FIELD3 CPUs${RESET}" >> $LOG
-      else
-        printf "%b\n" "  ${GREEN}$COUNT CPUs as expected${RESET}" >> $LOG
-      fi
+      check_cpus
     fi
     
     if [[ $FIELD2 = 'Memory' ]]
     then
-      check_memory()
+      check_memory
     fi
     
     if [[ $FIELD2 = 'IP' ]]
     then
-      if [[ ! ${DEBUG} = 'no' ]]
-      then
-        echo "Entering IP check"
-      fi
-      if [[ $OS = 'Linux' ]]
-      then
-        OUTPUT=`ip addr | grep " ${FIELD3}/"`
-      fi
-      if [[ ! -z $OUTPUT ]]
-      then
-        INTERFACE=`egrep "(\"|)${FIELD3}(\"|)$" /etc/sysconfig/network-scripts/ifcfg-* | cut -f1 -d: | cut -f3 -d-`
-        printf "%b\n" "  ${GREEN}IP $FIELD3 configured as ${INTERFACE}${RESET}" >> $LOG
-        egrep -i "onboot.*yes" /etc/sysconfig/network-scripts/ifcfg-${INTERFACE} > /dev/null
-        if [[ $? = 0 ]]
-        then
-          printf "%b\n" "    ${GREEN}${INTERFACE} is configured to start on boot${RESET}" >> $LOG
-        else
-          printf "%b\n" "    ${RED}${INTERFACE} is not configured to start on boot${RESET}" >> $LOG
-        fi
-        grep -i ${FIELD3} /etc/hosts > /dev/null
-        if [[ $? = 1 ]]
-        then
-          printf "%b\n" "    ${YELLOW}${FIELD3} is not in /etc/hosts${RESET}" >> $LOG
-        fi
-        PRIVATE=`ipcalc -n ${FIELD4}/24 | cut -f2 -d=`
-        if [[ ${PRIVATE} = '192.168.0.0' ]]
-        then
-        printf "%b\n" "    ${GREEN}Gateway ${FIELD4} is on a Private network${RESET}" >> $LOG
-        else
-          echo "  ping check of the gateway: ${FIELD4}"
-          ping ${FIELD4} ${PINGCT} > /dev/null 2>&1
-          if [[ $? = 0 ]]
-          then
-            printf "%b\n" "    ${GREEN}Gateway ${FIELD4} accessible${RESET}" >> $LOG
-          else
-            printf "%b\n" "    ${RED}Gateway ${FIELD4} is not responding to ping${RESET}" >> $LOG
-          fi
-        fi
-        GATEWAY="${GATEWAY} ${FIELD4}"
-        grep "GATEWAY=${FIELD4}" /etc/sysconfig/network > /dev/null
-        if [[ $? = 0 ]]
-        then
-          GWMSG="${GWMSG}    ${GREEN}/etc/sysconfig/network:GATEWAY=${FIELD4} configured${RESET}\n"
-          GWFLAG='yes'
-        fi
-# check the interface file too
-        grep "GATEWAY=${FIELD4}" /etc/sysconfig/network-scripts/ifcfg-${INTERFACE} > /dev/null
-        if [[ $? = 0 ]]
-        then
-          GWMSG="${GWMSG}    ${GREEN}/etc/sysconfig/network-scripts/ifcfg-${INTERFACE}:GATEWAY=${FIELD4} configured${RESET}\n"
-          GWFLAG='yes'
-        fi
-      else
-        printf "%b\n" "  ${RED}Unable to locate ${FIELD3} in ip addr output${RESET}" >> $LOG
-      fi
+      check_addresses
     fi
-
 
     if [[ $FIELD2 = 'Service' ]]
     then
