Added to config and fixed variables

diff --git a/bin/incowk01 b/bin/incowk01
--- a/bin/incowk01
+++ b/bin/incowk01
@@ -8,7 +8,18 @@
 # 01/20/14 - add wireless_mobility_wiki to pneteam listing
 # 01/27/16 - add v911 to pneteam listing
 
-WHOCARES=unixadmins@intrado.com
+#BASENAME=$(basename "${0}")
+DIRNAME=$(dirname "${0}")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
 WHOCARES=carl.schelin@intrado.com
 
 #
@@ -46,9 +57,9 @@ WHOCARES=carl.schelin@intrado.com
 #
 # validate the databases and report any errors
 #
-/usr/bin/mysqlcheck --user=root --password='this4now!!' -A > /opt/intrado/etc/mysql.output
+/usr/bin/mysqlcheck --user=root --password='this4now!!' -A > ${SCRIPTS_LOGS}/mysql.output
 
-OUTPUT=`grep -v "OK$" /opt/intrado/etc/mysql.output | grep -v "The storage engine for the table doesn't support check" | egrep -v "(^warning|^error|hitcounter)"`
+OUTPUT=`grep -v "OK$" ${SCRIPTS_LOGS}/mysql.output | grep -v "The storage engine for the table doesn't support check" | egrep -v "(^warning|^error|hitcounter)"`
 
 if [[ ! -z $OUTPUT ]]
 then
@@ -62,6 +73,6 @@ then
     BODY="${BODY}myisamchk -r $INDEX"
   done
 
-  echo $BODY | mail -s "Wiki Mysql Errors Found" $WHOCARES
+  echo $BODY | mail -s "Wiki Mysql Errors Found" "${WHOCARES}"
 fi
 
