Updated to correct variables

diff --git a/bin/lnmtcodccl20 b/bin/lnmtcodccl20
--- a/bin/lnmtcodccl20
+++ b/bin/lnmtcodccl20
@@ -4,27 +4,38 @@
 # system specific script to run system unique commands
 # 2014-01-31 - Script created to validate the querycarl script has been unmodified.
 
+BASENAME=$(basename "$0")
+DIRNAME=$(dirname "$0")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
 PROG=querycarl
 WHOCARES=unixadmins@intrado.com
 QUERY=/usr/local/bin/$PROG
-INTRADO=/opt/intrado
-DATE=`date +"%Y%m%d"`
+DATE=$(date +"%Y%m%d")
 
-if [[ -f $QUERY ]]
+if [[ -f ${QUERY} ]]
 then
-  /usr/bin/diff $QUERY $INTRADO/bin/$PROG > $INTRADO/var/$PROG.diff
+  /usr/bin/diff ${QUERY} "${SCRIPTS}/bin/${PROG}" > "${SCRIPTS}/var/${PROG}.diff"
 
-  if [[ -s $INTRADO/var/$PROG.diff ]]
+  if [[ -s ${SCRIPTS}/var/${PROG}.diff ]]
   then
-    cat $INTRADO/var/$PROG.diff | /usr/bin/mailx -s "$PROG has changed!" $WHOCARES
-    cp -p $QUERY $INTRADO/var/$PROG.$DATE
-    cp -p $INTRADO/bin/$PROG $QUERY
+    /usr/bin/mailx -s "${PROG} has changed!" ${WHOCARES} < "${SCRIPTS}/var/${PROG}.diff"
+    cp -p ${QUERY} "${SCRIPTS}/var/${PROG}.${DATE}"
+    cp -p "${SCRIPTS}/bin/${PROG}" ${QUERY}
 
   fi
 
 else
-  echo "$PROG not found!" | /usr/bin/mailx -s"$PROG not found!" $WHOCARES
-  cp -p $INTRADO/bin/$PROG $QUERY
+  echo "${PROG} not found!" | /usr/bin/mailx -s"${PROG} not found!" ${WHOCARES}
+  cp -p "${SCRIPTS}/bin/${PROG}" ${QUERY}
 
 fi
 
