Added mysql checks

diff --git a/bin/miam1cuomtool10 b/bin/miam1cuomtool10
--- a/bin/miam1cuomtool10
+++ b/bin/miam1cuomtool10
@@ -2,6 +2,21 @@
 
 # Carl Schelin
 # Delete kubernetes config files every night at 1am.
+# check mysql for errors
+
+#BASENAME=$(basename "${0}")
+DIRNAME=$(dirname "${0}")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
+WHOCARES=carl.schelin@intrado.com
 
 for i in `cat /usr/local/admin/kubernetes/userlist | cut -f1 -d:`
 do
@@ -14,4 +29,26 @@ do
     rm /var/www/html/kubernetes/$i.kubeconfig.zip
   fi
 done
+
+#
+# validate the databases and report any errors
+#
+/usr/bin/mysqlcheck --user=root --password='this4now!!' -A > ${SCRIPTS_LOGS}/mysql.output
+
+OUTPUT=`grep -v "OK$" ${SCRIPTS_LOGS}/mysql.output | grep -v "The storage engine for the table doesn't support check" | egrep -v "(^warning|^error|hitcounter)"`
+
+if [[ ! -z $OUTPUT ]]
+then
+  BODY="Wiki Mysql Errors Found"
+  for i in $OUTPUT
+  do
+    DIR=`echo $i|cut -f1 -d.`
+    INDEX=`echo $i|cut -f2 -d.`.MYI
+
+    BODY="${BODY}cd /var/lib/mysql/$DIR"
+    BODY="${BODY}myisamchk -r $INDEX"
+  done
+
+  echo $BODY | mail -s "Wiki Mysql Errors Found" "${WHOCARES}"
+fi
 
