Updated to fix intrado and nagios locations to use varaibles

diff --git a/bin/status b/bin/status
--- a/bin/status
+++ b/bin/status
@@ -5,13 +5,25 @@
 # 1/9/17 TCS - updated to not restart nagios if an error occurs with the scripts
 # 3/10/17 KSZ - Updated to use systemctl instead of service and added notification incase of restart failure
 
+BASENAME=$(basename "$0")
+DIRNAME=$(dirname "$0")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
 TMPDIR=/var/tmp
 NAGIOS=/usr/local/nagios
 NAGOBJ=$NAGIOS/etc/objects
 WHOCARES=unixadmins@intrado.com
 RESTART=no
 # Day of Week 1=Monday, 7=Sunday
-DOWEEK=`date +"%u"`
+DOWEEK=$(date +"%u")
 
 if [[ ! -z $1 ]]
 then
@@ -20,52 +32,52 @@ fi
 
 for i in loms sqa lab prod switch
 do
-  if [[ -f $TMPDIR/monitor.$i.cfg ]]
+  if [[ -f ${TMPDIR}/monitor.${i}.cfg ]]
   then
-    if [[ ! -f $NAGOBJ/monitor.$i.cfg ]]
+    if [[ ! -f ${NAGOBJ}/monitor.${i}.cfg ]]
     then
-      touch $NAGOBJ/monitor.$i.cfg
+      touch ${NAGOBJ}/monitor.${i}.cfg
     fi
 
-    diff $TMPDIR/monitor.$i.cfg $NAGOBJ/monitor.$i.cfg > $TMPDIR/monitor.$i.diff
+    diff ${TMPDIR}/monitor.${i}.cfg ${NAGOBJ}/monitor.${i}.cfg > $TMPDIR/monitor.${i}.diff
 
-    if [[ -s $TMPDIR/monitor.$i.diff ]]
+    if [[ -s ${TMPDIR}/monitor.${i}.diff ]]
     then
-      cp $TMPDIR/monitor.$i.cfg $NAGOBJ/monitor.$i.cfg
+      cp ${TMPDIR}/monitor.${i}.cfg $NAGOBJ/monitor.${i}.cfg
       RESTART=yes
     fi
   fi
 done
 
 
-if [[ $RESTART = 'yes' ]]
+if [[ ${RESTART} = 'yes' ]]
 then
 
-  /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg > /opt/intrado/etc/nagios.output
+  ${NAGIOS}/bin/nagios -v ${NAGIOS}/etc/nagios.cfg > "${SCRIPTS}"/etc/nagios.output
 
   if [[ $? = 0 ]]
   then
     systemctl is-active nagios > /dev/null 2>&1 && systemctl restart nagios || systemctl start nagios
     if [[ $? != 0 || ! $(systemctl is-failed nagios) ]]; then
-      systemctl status nagios | mailx -s "Nagios restart failure" $WHOCARES
+      systemctl status nagios | mailx -s "Nagios restart failure" ${WHOCARES}
     fi
   else
-    cat /opt/intrado/etc/nagios.output | mailx -s "Nagios configuration error" $WHOCARES
+    mailx -s "Nagios configuration error" ${WHOCARES} < "${SCRIPTS}"/etc/nagios.output
   fi  
 else
 # restart every Monday just to be sure.
-  if [[ $DOWEEK = 1 ]]
+  if [[ ${DOWEEK} = 1 ]]
   then
-    /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg > /opt/intrado/etc/nagios.output
+    ${NAGIOS}/bin/nagios -v ${NAGIOS}/etc/nagios.cfg > "${SCRIPTS}"/etc/nagios.output
 
     if [[ $? = 0 ]]
     then
       systemctl is-active nagios > /dev/null 2>&1 && systemctl restart nagios || systemctl start nagios
       if [[ $? != 0 || ! $(systemctl is-failed nagios) ]]; then
-        systemctl status nagios | mailx -s "Nagios restart failure" $WHOCARES
+        systemctl status nagios | mailx -s "Nagios restart failure" ${WHOCARES}
       fi
     else 
-      cat /opt/intrado/etc/nagios.output | mailx -s "Nagios configuration error" $WHOCARES
+      mailx -s "Nagios configuration error" ${WHOCARES} < "${SCRIPTS}"/etc/nagios.output
     fi
   fi
 fi
