standardizing the update shell scripts

diff --git a/kubernetes/09-destroy/update b/kubernetes/09-destroy/update
--- a/kubernetes/09-destroy/update
+++ b/kubernetes/09-destroy/update
@@ -18,12 +18,20 @@ function usage() {
   echo "    Production sites: lnmt1-2 miam1-1"
 }
 
+if [[ $(id -u) -ne 5000 ]]
+then
+  echo "This script must be run by the unixsvc account."
+  echo ""
+  exit 1
+fi
+
 if [[ -z $1 ]]
 then
   usage
   exit 0
 fi
 
+HOSTS="/usr/local/admin/etc/hosts"
 OPTCHECK=''
 OPTSITE=''
 while getopts "ehs:" arg
@@ -43,6 +51,13 @@ done
 if [[ -f *.retry ]]
 then
   rm *.retry
+fi
+
+if [[ ! -f ${HOSTS} ]]
+then
+  echo "You are not on an ansible server. ${HOSTS} not found."
+  echo ""
+  exit 1
 fi
 
 if [[ -z ${OPTSITE} ]]
@@ -66,5 +81,11 @@ echo ""
 echo "Are you absolutely sure you want to DESTROY the $OPTSITE cluster? Break out of the script now if this is in error."
 read
 
-ansible-playbook -i /usr/local/admin/etc/hosts ${OPTCHECK} -e site=${OPTSITE} destroy.yaml -s 
+/usr/local/bin/searchansible ${OPTSITE} > /dev/null 2>&1
+if [[ $? -eq 0 ]]
+then
+  ansible-playbook -i /usr/local/admin/etc/hosts ${OPTCHECK} -e site=${OPTSITE} destroy.yaml -s 
+else
+  echo "Unable to locate ${OPTSITE} in the ${HOSTS} hosts file"
+fi
 
