Updated to use pattern for the passed pattern of hosts and to fix the update scripts

diff --git a/ELK/data/update b/ELK/data/update
--- a/ELK/data/update
+++ b/ELK/data/update
@@ -2,7 +2,7 @@
 
 # Carl Schelin
 # update:
-# Defining the master Elastic Stack servers
+# Update 
 
 function usage() {
   echo "Usage:"
@@ -10,7 +10,9 @@ function usage() {
   echo "where:"
   echo " -h help"
   echo " -e enable check - Enable --check to validate task"
-  echo " -t tag of the servers to be updated"
+  echo " -t tag - Tag for the list of servers"
+  echo "  Run searchansible to see all tags"
+  echo "  Run searchansible [tag] to see the servers associated with [tag]"
 }
 
 if [[ $(id -u) -ne 5000 ]]
@@ -26,6 +28,7 @@ then
   exit 0
 fi
 
+PLAYBOOK=data.yaml
 HOSTS="/usr/local/admin/etc/hosts"
 OPTCHECK=''
 OPTTAG=''
@@ -57,7 +60,7 @@ fi
 
 if [[ -z ${OPTTAG} ]]
 then
-  echo "Error: No tag enterred"
+  echo "Error: No configured site: ${OPTTAG}"
   echo ""
   usage
   exit 1
@@ -68,6 +71,12 @@ then
   echo "Validation enabled. No changes will be made to the systems."
 fi
 
-echo "Create Elasticsearch Data nodes"
-ansible-playbook -i ${HOSTS} ${OPTCHECK} -e tag=${OPTTAG} data.yaml
+/usr/local/bin/searchansible ${OPTSITE} > /dev/null 2>&1
+if [[ $? -eq 0 ]]
+then
+  echo "Update sshd"
+  ansible-playbook -i ${HOSTS} ${OPTCHECK} -e pattern=${OPTTAG} ${PLAYBOOK}
+else
+  echo "Unable to locate ${OPTTAG} in the ${HOSTS} hosts file"
+fi
 
diff --git a/ELK/kibana/update b/ELK/kibana/update
--- a/ELK/kibana/update
+++ b/ELK/kibana/update
@@ -2,7 +2,7 @@
 
 # Carl Schelin
 # update:
-# Install Kibana on the Elastic Stack servers
+# Update 
 
 function usage() {
   echo "Usage:"
@@ -10,8 +10,17 @@ function usage() {
   echo "where:"
   echo " -h help"
   echo " -e enable check - Enable --check to validate task"
-  echo " -t tag to use"
+  echo " -t tag - Tag for the list of servers"
+  echo "  Run searchansible to see all tags"
+  echo "  Run searchansible [tag] to see the servers associated with [tag]"
 }
+
+if [[ $(id -u) -ne 5000 ]]
+then
+  echo "This script must be run by the unixsvc account."
+  echo ""
+  exit 1
+fi
 
 if [[ -z $1 ]]
 then
@@ -19,10 +28,10 @@ then
   exit 0
 fi
 
+PLAYBOOK=kibana.yaml
 HOSTS="/usr/local/admin/etc/hosts"
 OPTCHECK=''
 OPTTAG=''
-OPTUSER=''
 while getopts "eht:" arg
 do
   case $arg in
@@ -42,9 +51,16 @@ then
   rm *.retry
 fi
 
+if [[ ! -f ${HOSTS} ]]
+then
+  echo "You are not on an ansible server. ${HOSTS} not found."
+  echo ""
+  exit 1
+fi
+
 if [[ -z ${OPTTAG} ]]
 then
-  echo "Error: No tag configured"
+  echo "Error: No configured site: ${OPTTAG}"
   echo ""
   usage
   exit 1
@@ -55,6 +71,12 @@ then
   echo "Validation enabled. No changes will be made to the systems."
 fi
 
-echo "Create Kibana Node"
-ansible-playbook -i ${HOSTS} ${OPTCHECK} -e tag=${OPTTAG} kibana.yaml
+/usr/local/bin/searchansible ${OPTSITE} > /dev/null 2>&1
+if [[ $? -eq 0 ]]
+then
+  echo "Update sshd"
+  ansible-playbook -i ${HOSTS} ${OPTCHECK} -e pattern=${OPTTAG} ${PLAYBOOK}
+else
+  echo "Unable to locate ${OPTTAG} in the ${HOSTS} hosts file"
+fi
 
diff --git a/ELK/logstash/update b/ELK/logstash/update
--- a/ELK/logstash/update
+++ b/ELK/logstash/update
@@ -2,20 +2,22 @@
 
 # Carl Schelin
 # update:
-# Install the logstash tools for the Elastic Stack servers
+# Update 
 
 function usage() {
   echo "Usage:"
-  echo "elastic -eht [tag]"
+  echo "update -eht [tag]"
   echo "where:"
   echo " -h help"
   echo " -e enable check - Enable --check to validate task"
-  echo " -t tag to use"
+  echo " -t tag - Tag for the list of servers"
+  echo "  Run searchansible to see all tags"
+  echo "  Run searchansible [tag] to see the servers associated with [tag]"
 }
 
 if [[ $(id -u) -ne 5000 ]]
 then
-  echo "Error: This script can only be run by the unixsvc account"
+  echo "This script must be run by the unixsvc account."
   echo ""
   exit 1
 fi
@@ -26,6 +28,7 @@ then
   exit 0
 fi
 
+PLAYBOOK=logstash.yaml
 HOSTS="/usr/local/admin/etc/hosts"
 OPTCHECK=''
 OPTTAG=''
@@ -48,18 +51,18 @@ then
   rm *.retry
 fi
 
-if [[ -z ${OPTTAG} ]]
+if [[ ! -f ${HOSTS} ]]
 then
-  echo "Error: No tag configured"
+  echo "You are not on an ansible server. ${HOSTS} not found."
   echo ""
-  usage
   exit 1
 fi
 
-if [[ ! -f ${HOSTS} ]]
+if [[ -z ${OPTTAG} ]]
 then
-  echo "Error: No ${HOSTS} file. Are you on the right server?"
+  echo "Error: No configured site: ${OPTTAG}"
   echo ""
+  usage
   exit 1
 fi
 
@@ -68,6 +71,12 @@ then
   echo "Validation enabled. No changes will be made to the systems."
 fi
 
-echo "Create Logstash Node"
-ansible-playbook -i ${HOSTS} ${OPTCHECK} -e tag=${OPTTAG} logstash.yaml
+/usr/local/bin/searchansible ${OPTSITE} > /dev/null 2>&1
+if [[ $? -eq 0 ]]
+then
+  echo "Update sshd"
+  ansible-playbook -i ${HOSTS} ${OPTCHECK} -e pattern=${OPTTAG} ${PLAYBOOK}
+else
+  echo "Unable to locate ${OPTTAG} in the ${HOSTS} hosts file"
+fi
 
