standardizing the scripts

diff --git a/snmp/update b/snmp/update
--- a/snmp/update
+++ b/snmp/update
@@ -17,12 +17,21 @@ function usage() {
   echo "    icl-0, bldr0-0, gldn0-0, cabo0-0, hell0-0, alde0-0, tato0-1, lnmt1-2, miam1-1"
 }
 
+if [[ $(id -u) -ne 5000 ]]
+then
+  echo "This script must be run by the unixsvc account."
+  echo ""
+  exit 1
+fi
+
 if [[ -z $1 ]]
 then
   usage
   exit 0
 fi
 
+HOSTS="/usr/local/admin/etc/hosts"
+OPTCHECK=''
 OPTSITE=''
 while getopts "ehs:" arg
 do
@@ -43,6 +52,13 @@ then
   rm *.retry
 fi
 
+if [[ ! -f ${HOSTS} ]]
+then
+  echo "You are not on an ansible server. ${HOSTS} not found."
+  echo ""
+  exit 1
+fi
+
 if [[ -z ${OPTSITE} ]]
 then
   echo "Error: No configured site: ${OPTSITE}"
@@ -55,8 +71,8 @@ fi
 if [[ $? -eq 0 ]]
 then
   echo "Update snmpd.conf information"
-  ansible-playbook -i ${HOSTFILE} --extra-vars "site=${OPTSITE}" ${OPTCHECK} snmpd.yaml -s
+  ansible-playbook -i ${HOSTS} --extra-vars "site=${OPTSITE}" ${OPTCHECK} snmpd.yaml -s
 else
-  echo "Unable to locate ${OPTSITE} in the ${HOSTFILE} hosts file"
+  echo "Unable to locate ${OPTSITE} in the ${HOSTS} hosts file"
 fi
 
