standardize the update shells script

diff --git a/kubernetes/06-certificates/update b/kubernetes/06-certificates/update
--- a/kubernetes/06-certificates/update
+++ b/kubernetes/06-certificates/update
@@ -2,7 +2,7 @@
 
 # Carl Schelin
 # update:
-# update the cluster name and other variables for the kubernetes servers
+# ensure the west and intrado certs are installed
 
 function usage() {
   echo "Usage:"
@@ -18,15 +18,21 @@ function usage() {
   echo "    Production sites: lnmt1-2 miam1-1"
 }
 
+if [[ $(id -u) -ne 5000 ]]
+then
+  echo "This script must be run by the unixsvc account."
+  echo ""
+  exit 1
+fi
+
 if [[ -z $1 ]]
 then
   usage
   exit 0
 fi
 
-OPTCHECK=''
+HOSTS="/usr/local/admin/etc/hosts"
 OPTSITE=''
-OPTUSER=''
 while getopts "ehs:" arg
 do
   case $arg in
@@ -46,6 +52,13 @@ then
   rm *.retry
 fi
 
+if [[ ! -f ${HOSTS} ]]
+then
+  echo "You are not on an ansible server. ${HOSTS} not found."
+  echo ""
+  exit 1
+fi
+
 if [[ -z ${OPTSITE} ]]
 then
   echo "Error: No configured site: ${OPTSITE}"
@@ -59,6 +72,12 @@ then
   echo "Validation enabled. No changes will be made to the systems."
 fi
 
-echo "Update Certificates"
-ansible-playbook -i /usr/local/admin/etc/hosts ${OPTCHECK} -e site=${OPTSITE} certificates.yaml -s 
+/usr/local/bin/searchansible ${OPTSITE} > /dev/null 2>&1
+if [[ $? -eq 0 ]]
+then
+  echo "Update Certificates"
+  ansible-playbook -i /usr/local/admin/etc/hosts ${OPTCHECK} -e site=${OPTSITE} certificates.yaml -s 
+else
+  echo "Unable to locate ${OPTSITE} in the ${HOSTS} hosts file"
+fi
 
