standardizing the scripts

diff --git a/chrony/update b/chrony/update
--- a/chrony/update
+++ b/chrony/update
@@ -4,8 +4,6 @@
 # update:
 # Update the chrony information on all servers
 
-HOSTFILE=/usr/local/admin/etc/hosts
-
 function usage() {
   echo "Usage:"
   echo "update -ehs [site] "
@@ -17,12 +15,21 @@ function usage() {
   echo "    icl-0, bldr0-0, gldn0-0, cabo0-0, hell0-0, alde0-0, tato0-1, lnmt1-2, miam1-1"
 }
 
+if [[ $(id -u) -ne 5000 ]]
+then
+  echo "This script must be run by the unixsvc account."
+  echo ""
+  exit 1
+fi
+
 if [[ -z $1 ]]
 then
   usage
   exit 0
 fi
 
+HOSTS="/usr/local/admin/etc/hosts"
+OPTCHECK=''
 OPTSITE=''
 while getopts "ehs:" arg
 do
@@ -43,6 +50,13 @@ then
   rm *.retry
 fi
 
+if [[ ! -f ${HOSTS} ]]
+then
+  echo "You are not on an ansible server. ${HOSTS} not found."
+  echo ""
+  exit 1
+fi
+
 if [[ -z ${OPTSITE} ]]
 then
   echo "Error: No configured site: ${OPTSITE}"
@@ -55,8 +69,40 @@ fi
 if [[ $? -eq 0 ]]
 then
   echo "Update chrony.conf information"
-  ansible-playbook -i ${HOSTFILE} --extra-vars "site=${OPTSITE}" ${OPTCHECK} chrony.yaml -s
+  ansible-playbook -i ${HOSTS} --extra-vars "site=${OPTSITE}" ${OPTCHECK} chrony.yaml -s
 else
-  echo "Unable to locate ${OPTSITE} in the ${HOSTFILE} hosts file"
+  echo "Unable to locate ${OPTSITE} in the ${HOSTS} hosts file"
+fi
+
+
+
+done
+
+# remove *.retry files
+if [[ -f *.retry ]]
+then
+  rm *.retry
+fi
+
+if [[ -z ${OPTSITE} ]]
+then
+  echo "Error: No configured site: ${OPTSITE}"
+  echo ""
+  usage
+  exit 1
+fi
+
+if [[ ! -z ${OPTCHECK} ]]
+then
+  echo "Validation enabled. No changes will be made to the systems."
+fi
+
+/usr/local/bin/searchansible ${OPTSITE} > /dev/null 2>&1
+if [[ $? -eq 0 ]]
+then
+  echo "Update sudoers and users"
+  ansible-playbook -i ${HOSTS} ${OPTCHECK} -e site=${OPTSITE} sudoers.yaml -s 
+else
+  echo "Unable to locate ${OPTSITE} in the ${HOSTS} hosts file"
 fi
 
