Updated to properly stop when called

diff --git a/run.d/chkkubernetes b/run.d/chkkubernetes
--- a/run.d/chkkubernetes
+++ b/run.d/chkkubernetes
@@ -26,6 +26,12 @@ then
   exit 1
 fi
 
+if [[ -f ${SCRIPTS_DATA}/chkkubernetes.stop ]]
+then
+  echo "Preventing the execution of the script."
+  exit 1
+fi
+
 WHOCARES="unixadmins.safetyservices@regmail.west.com"
 WHOCARES="unixadmins-oncall.safetyservices@regmail.west.com"
 WHOCARES="cschelin@west.com"
@@ -58,91 +64,105 @@ then
   KUBE_WORKER_KEY_FILE="worker-key.pem"
 fi
 
-# are we on a system being monitored?
-if [[ ! -z ${KUBE_CONTEXT} ]]
+# need to check the chkkubernetes.input listing
+# if none:none, then just exit
+# if can't find the context, exit
+
+
+
+if [[ -z ${KUBE_CONTEXT} ]]
 then
-  CHKSYS=`grep "^${HOSTNAME}:" ${SCRIPTS}/etc/chkkubernetes.input`
+  echo "Context not found, exiting"
+  exit 1
+fi
+
+OUTPUT=`grep "^${HOSTNAME}:" ${SCRIPTS_DATA}/chkkubernetes.input | cut -f4 -d:`
+if [[ $OUTPUT = "none" ]]
+then
+  echo "No checking requested"
+  exit 1
+fi
+
+# are we on a system being monitored?
+CHKSYS=`grep "^${HOSTNAME}:" ${SCRIPTS}/etc/chkkubernetes.input`
 
 # check the status of etcd
-  etcdctl \
-    --ca-file=${KUBE_ETCD_CERTS}/${KUBE_CA_FILE} \
-    --key-file=${KUBE_ETCD_CERTS}/${KUBE_WORKER_KEY_FILE} \
-    --cert-file=${KUBE_ETCD_CERTS}/${KUBE_WORKER_FILE} \
-    --endpoint=https://${INTERNAL_IP}:2379 \
-    cluster-health > /dev/null
+etcdctl \
+  --ca-file=${KUBE_ETCD_CERTS}/${KUBE_CA_FILE} \
+  --key-file=${KUBE_ETCD_CERTS}/${KUBE_WORKER_KEY_FILE} \
+  --cert-file=${KUBE_ETCD_CERTS}/${KUBE_WORKER_FILE} \
+  --endpoint=https://${INTERNAL_IP}:2379 \
+  cluster-health > /dev/null
 
-  if [[ $? -eq 0 ]]
-  then
-    echo "etcd cluster healthy"
-  else
-    echo "etcd cluster is not healthy"
-  fi
+if [[ $? -eq 0 ]]
+then
+  echo "etcd cluster healthy"
+else
+  echo "etcd cluster is not healthy"
+fi
 
 # check the status of the local api server
-  curl \
-    -vvv \
-    --cert ${KUBE_KUBERNETES_CERTS}/${KUBE_WORKER_FILE} \
-    --key ${KUBE_KUBERNETES_CERTS}/${KUBE_WORKER_KEY_FILE} \
-    --cacert ${KUBE_KUBERNETES_CERTS}/${KUBE_CA_FILE} \
-    https://${INTERNAL_IP}:${KUBE_API_SERVER_PORT}/version > /dev/null 2>&1
+curl \
+  -vvv \
+  --cert ${KUBE_KUBERNETES_CERTS}/${KUBE_WORKER_FILE} \
+  --key ${KUBE_KUBERNETES_CERTS}/${KUBE_WORKER_KEY_FILE} \
+  --cacert ${KUBE_KUBERNETES_CERTS}/${KUBE_CA_FILE} \
+  https://${INTERNAL_IP}:${KUBE_API_SERVER_PORT}/version > /dev/null 2>&1
 
-  if [[ $? -eq 0 ]]
-  then
-    echo "Local apiserver query reply success"
-  else
-    echo "Local apiserver query failed"
-  fi
+if [[ $? -eq 0 ]]
+then
+  echo "Local apiserver query reply success"
+else
+  echo "Local apiserver query failed"
+fi
 
+curl \
+  -k \
+  -vvv \
+  -cert ${KUBE_KUBERNETES_CERTS}/${KUBE_WORKER_FILE} \
+  -key ${KUBE_KUBERNETES_CERTS}/${KUBE_WORKER_KEY_FILE} \
+  -cacert ${KUBE_KUBERNETES_CERTS}/${KUBE_CA_FILE} \
+  https://${KUBE_API_SERVER}:${KUBE_API_SERVER_PORT}/version > /dev/null 2>&1
 
-  curl \
-    -k \
-    -vvv \
-    -cert ${KUBE_KUBERNETES_CERTS}/${KUBE_WORKER_FILE} \
-    -key ${KUBE_KUBERNETES_CERTS}/${KUBE_WORKER_KEY_FILE} \
-    -cacert ${KUBE_KUBERNETES_CERTS}/${KUBE_CA_FILE} \
-    https://${KUBE_API_SERVER}:${KUBE_API_SERVER_PORT}/version > /dev/null 2>&1
+if [[ $? -eq 0 ]]
+then
+  echo "apiserver VIP query success"
+else
+  echo "apiserver VIP query failed"
+fi
 
-  if [[ $? -eq 0 ]]
-  then
-    echo "apiserver VIP query success"
-  else
-    echo "apiserver VIP query failed"
-  fi
-
-  for i in $(kubectl get nodes | grep -v NAME | awk '{print $1":"$2}')
-  do
-    NODE=$(echo $i | cut -f1 -d:)
+for i in $(kubectl get nodes | grep -v NAME | awk '{print $1":"$2}')
+do
+  NODE=$(echo $i | cut -f1 -d:)
 # management nodes are 'Ready,SchedulingDisabled'; just looking for 'Ready' or not.
-    STATUS=$(echo $i | cut -f2 -d: | cut -f1 -d,)
+  STATUS=$(echo $i | cut -f2 -d: | cut -f1 -d,)
 
-    if [[ ! ${STATUS} = 'Ready' ]]
+  if [[ ! ${STATUS} = 'Ready' ]]
+  then
+    echo "Node ${NODE} is currently not in Ready state (${STATUS}) kubectl describe node ${NODE}"
+  fi
+done
+
+for i in $(kubectl get namespaces | grep Active | egrep -v "(NAME|default)")
+do
+  FLAG=0
+  for j in $(kubectl --namespace=${i} get pods | awk '{print $1":"$2":"$3":"$4}')
+  do
+    CONTAINER=$(echo ${j} | cut -f1 -d:)
+    ACTIVE=$(echo ${j} | cut -f2 -d: | cut -f1 -d/)
+    EXPECTED=$(echo ${j} | cut -f2 -d: | cut -f2 -d/)
+    ERROR=$(echo ${j} | cut -f3 -d:)
+    DAYS=$(echo ${j} | cut -f4 -d:)
+
+    if [[ ${ACTIVE} -ne ${EXPECTED} ]]
     then
-      echo "Node ${NODE} is currently not in Ready state (${STATUS}) kubectl describe node ${NODE}"
+      if [[ ${FLAG} -eq 0 ]]
+      then
+        echo "Namespace ${i} is reporting errors:"
+        FLAG=1
+      fi
+      echo "Container ${CONTAINER} has failed. ${ACTIVE} of ${EXPECTED} containers are running. Reported error: ${ERROR}"
     fi
   done
-
-  for i in $(kubectl get namespaces | grep Active | egrep -v "(NAME|default)")
-  do
-    FLAG=0
-    for j in $(kubectl --namespace=${i} get pods | awk '{print $1":"$2":"$3":"$4}')
-    do
-      CONTAINER=$(echo ${j} | cut -f1 -d:)
-      ACTIVE=$(echo ${j} | cut -f2 -d: | cut -f1 -d/)
-      EXPECTED=$(echo ${j} | cut -f2 -d: | cut -f2 -d/)
-      ERROR=$(echo ${j} | cut -f3 -d:)
-      DAYS=$(echo ${j} | cut -f4 -d:)
-
-      if [[ ${ACTIVE} -ne ${EXPECTED} ]]
-      then
-        if [[ ${FLAG} -eq 0 ]]
-        then
-          echo "Namespace ${i} is reporting errors:"
-          FLAG=1
-        fi
-        echo "Container ${CONTAINER} has failed. ${ACTIVE} of ${EXPECTED} containers are running. Reported error: ${ERROR}"
-      fi
-    done
-  done
-
-fi
+done
 
