standardizing the update shell scripts

diff --git a/kubernetes/08-permissions/update b/kubernetes/08-permissions/update
--- a/kubernetes/08-permissions/update
+++ b/kubernetes/08-permissions/update
@@ -19,12 +19,20 @@ function usage() {
   echo "    Production sites: lnmt1-2 miam1-1"
 }
 
+if [[ $(id -u) -ne 5000 ]]
+then
+  echo "This script must be run by the unixsvc account."
+  echo ""
+  exit 1
+fi
+
 if [[ -z $1 ]]
 then
   usage
   exit 0
 fi
 
+HOSTS="/usr/local/admin/etc/hosts"
 OPTSITE=''
 while getopts "ehs:" arg
 do
@@ -43,6 +51,13 @@ done
 if [[ -f *.retry ]]
 then
   rm *.retry
+fi
+
+if [[ ! -f ${HOSTS} ]]
+then
+  echo "You are not on an ansible server. ${HOSTS} not found."
+  echo ""
+  exit 1
 fi
 
 if [[ -z ${OPTSITE} ]]
